/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nhap;

import com.database.DB;
import com.home.HomeFrame;
import com.home.HomeFrameAdmin;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Desktop;

import java.io.IOException;

/**
 *
 * @author Jacker
 */
public class NhapFrame extends javax.swing.JFrame {

    /**
     * Creates new form NhapFrame
     */
    public NhapFrame() {
        initComponents();
        loadTable();
    }
    
    
    public void loadAllDataIntoTable(List<NhapBean> list){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        for(NhapBean bean : list) {
            Vector v = new Vector();
            v.add(bean.getIdsanpham());
            v.add(bean.getTenSanPham());
            v.add(bean.getNhaCungCap());
            v.add(bean.getGiaNhap());
            v.add(bean.getNgayNhap());
            v.add(bean.getSize());
            v.add(bean.getMau());
            v.add(bean.getSoLuong());
            
            dtm.addRow(v);
        
        }
        
    
    }
    
    public void loadTable(){
        NhapBal bal = new NhapBal();
        List list = bal.loadData();
        loadAllDataIntoTable(list);
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jTextFieldTenSanPham = new javax.swing.JTextField();
        jTextFieldNhaCungCap = new javax.swing.JTextField();
        jTextFieldGiaNhap = new javax.swing.JTextField();
        jTextFieldSize = new javax.swing.JTextField();
        jTextFieldMau = new javax.swing.JTextField();
        jTextFieldNgayNhap = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1070, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ NHẬP XUẤT QUẦN ÁO");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nhập mã hàng hóa để in");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("In phiếu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton3)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 90));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1060, 70));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 102));
        jPanel3.setToolTipText("Nhập thông tin hàng");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Nhà cung cấp");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Giá nhập");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Ngày nhập");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Size");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Màu");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Số lượng");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("Tên sản phẩm");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 30));

        jTextFieldSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoLuongActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 220, 30));

        jTextFieldTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTenSanPhamActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 220, 30));

        jTextFieldNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNhaCungCapActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 220, 30));

        jTextFieldGiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGiaNhapActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldGiaNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, 30));

        jTextFieldSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSizeActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, 30));

        jTextFieldMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMauActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldMau, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 220, 30));

        jTextFieldNgayNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNgayNhapActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 220, 30));

        jButtonInsert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonInsert.setForeground(new java.awt.Color(0, 153, 153));
        jButtonInsert.setText("Nhập hàng");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 140, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 130, -1));

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(0, 153, 153));
        jButtonDelete.setText("Xóa");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 130, -1));

        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(0, 153, 153));
        jButtonUpdate.setText("Cập nhật");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 140, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, 450));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Nhà cung cấp", "Giá nhập", "Ngày nhập", "Size", "Màu", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 640, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoLuongActionPerformed

    private void jTextFieldTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTenSanPhamActionPerformed

    private void jTextFieldNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNhaCungCapActionPerformed

    private void jTextFieldGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGiaNhapActionPerformed

    private void jTextFieldSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSizeActionPerformed

    private void jTextFieldMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMauActionPerformed

    private void jTextFieldNgayNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNgayNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNgayNhapActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // TODO add your handling code here:
        
        try {
            String TenSanPham = jTextFieldTenSanPham.getText().trim();
            String NhaCungCap = jTextFieldNhaCungCap.getText().trim();
            String GiaNhapStr = jTextFieldGiaNhap.getText().trim();
            String NgayNhap = jTextFieldNgayNhap.getText().trim();
            String Size = jTextFieldSize.getText().trim();
            String Mau = jTextFieldMau.getText().trim();
            String SoLuongStr = jTextFieldSoLuong.getText().trim();

            // Kiểm tra rỗng
            if (TenSanPham.isEmpty() || NhaCungCap.isEmpty() || GiaNhapStr.isEmpty() || NgayNhap.isEmpty()
                    || Size.isEmpty() || Mau.isEmpty() || SoLuongStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ tất cả các trường.", "Thiếu thông tin", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra trường phải là chữ (cho phép khoảng trắng, không số)
            if (!TenSanPham.matches("[\\p{L} ]+")) {
                JOptionPane.showMessageDialog(this, "Tên sản phẩm chỉ được chứa chữ cái.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!NhaCungCap.matches("[\\p{L} ]+")) {
                JOptionPane.showMessageDialog(this, "Nhà cung cấp chỉ được chứa chữ cái.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!Mau.matches("[\\p{L} ]+")) {
                JOptionPane.showMessageDialog(this, "Màu chỉ được chứa chữ cái.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!Size.matches("[\\p{L}0-9]+")) { // Nếu Size là chữ + số như "XL", "42", giữ nguyên regex này
                JOptionPane.showMessageDialog(this, "Size chỉ được chứa chữ cái và/hoặc số, không có ký tự đặc biệt.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra định dạng số
            float GiaNhap;
            int SoLuong;
            try {
                GiaNhap = Float.parseFloat(GiaNhapStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Giá nhập phải là một số hợp lệ.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                SoLuong = Integer.parseInt(SoLuongStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số lượng phải là một số nguyên hợp lệ.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra định dạng ngày
            if (!NgayNhap.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(this, "Ngày nhập phải có định dạng yyyy-MM-dd (VD: 2025-05-21).", "Lỗi định dạng ngày", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Tạo Bean và insert nếu mọi thứ hợp lệ
            NhapBean nhapBean = new NhapBean(0, TenSanPham, NhaCungCap, GiaNhap, NgayNhap, Size, Mau, SoLuong);
            NhapBal nhapObj = new NhapBal();
            nhapObj.insert(nhapBean);
            loadTable();
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        new HomeFrame().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String maHangHoa = jTextField8.getText().trim();
    if (maHangHoa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã hàng hóa");
        return;
    }

    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/world", "root", "123456")) {
        String query = "SELECT * FROM hanghoa WHERE MaHangHoa = ?";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, maHangHoa);
        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // Tạo tài liệu PDF
            Document document = new Document();
            String filePath = "phieu_" + maHangHoa + ".pdf";
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();

            // Tiêu đề
            Font titleFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
            Paragraph title = new Paragraph("PHIẾU HÀNG HÓA\n\n", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            // Nội dung
            Font contentFont = new Font(Font.FontFamily.TIMES_ROMAN, 12);
            document.add(new Paragraph("Mã hàng hóa: " + rs.getInt("MaHangHoa"), contentFont));
            document.add(new Paragraph("Tên hàng hóa: " + rs.getString("TenHangHoa"), contentFont));
            document.add(new Paragraph("Loại hàng hóa: " + rs.getString("LoaiHangHoa"), contentFont));
            document.add(new Paragraph("Xuất xứ: " + rs.getString("XuatXu"), contentFont));
            document.add(new Paragraph("Ngày sản xuất: " + rs.getString("NgaySanXuat"), contentFont));
            document.add(new Paragraph("Giá bán: " + rs.getFloat("GiaBan") + " VND", contentFont));
            document.add(new Paragraph("Số lượng: " + rs.getInt("SoLuong"), contentFont));

            document.close();
            
            // Tự động mở phiếu
            try {
                File pdfFile = new File(filePath);
                if (pdfFile.exists() && Desktop.isDesktopSupported()) {
                    Desktop.getDesktop().open(pdfFile);  // Mở file PDF bằng trình mặc định của hệ điều hành
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể mở file PDF tự động.");
                }
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khi mở file PDF.");
            }

            JOptionPane.showMessageDialog(this, "Đã tạo phiếu PDF thành công tại: " + filePath);

        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy hàng hóa với mã: " + maHangHoa);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi tạo file PDF.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    int id=0;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row<0) {
            JOptionPane.showMessageDialog(null, "Chọn cột có dữ liệu");
            
        }else{
            id = (int) jTable1.getValueAt(row, 0);
            NhapBal bal= new NhapBal();
            NhapBean bean = bal.returnAllDataToTextFields(id);
            jTextFieldTenSanPham.setText(bean.getTenSanPham());
            jTextFieldNhaCungCap.setText(bean.getNhaCungCap());
            jTextFieldGiaNhap.setText(""+bean.getGiaNhap());
            jTextFieldNgayNhap.setText(bean.getNgayNhap());
            jTextFieldSize.setText(bean.getSize());
            jTextFieldMau.setText(bean.getMau());
            jTextFieldSoLuong.setText(""+bean.getSoLuong());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        

        NhapBal bal = new NhapBal();
        bal.deleteData(id);
        loadTable();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String TenSanPham = jTextFieldTenSanPham.getText().trim();
            String NhaCungCap = jTextFieldNhaCungCap.getText().trim();
            String GiaNhapStr = jTextFieldGiaNhap.getText().trim();
            String NgayNhap = jTextFieldNgayNhap.getText().trim();
            String Size = jTextFieldSize.getText().trim();
            String Mau = jTextFieldMau.getText().trim();
            String SoLuongStr = jTextFieldSoLuong.getText().trim();

            // Kiểm tra rỗng
            if (TenSanPham.isEmpty() || NhaCungCap.isEmpty() || GiaNhapStr.isEmpty()
                    || NgayNhap.isEmpty() || Size.isEmpty() || Mau.isEmpty() || SoLuongStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ tất cả các trường.", "Thiếu thông tin", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra các trường phải là chữ
            if (!TenSanPham.matches("[\\p{L} ]+")) {
                JOptionPane.showMessageDialog(this, "Tên sản phẩm chỉ được chứa chữ cái.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!NhaCungCap.matches("[\\p{L} ]+")) {
                JOptionPane.showMessageDialog(this, "Nhà cung cấp chỉ được chứa chữ cái.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!Mau.matches("[\\p{L} ]+")) {
                JOptionPane.showMessageDialog(this, "Màu chỉ được chứa chữ cái.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra Size hợp lệ
            if (!Size.matches("[\\p{L}0-9]+")) {
                JOptionPane.showMessageDialog(this, "Size chỉ được chứa chữ và/hoặc số, không có ký tự đặc biệt.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra định dạng số
            float GiaNhap;
            int SoLuong;
            try {
                GiaNhap = Float.parseFloat(GiaNhapStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Giá nhập phải là số hợp lệ.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                SoLuong = Integer.parseInt(SoLuongStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên hợp lệ.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Kiểm tra định dạng ngày
            if (!NgayNhap.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(this, "Ngày nhập phải có định dạng yyyy-MM-dd (VD: 2025-05-21).", "Lỗi định dạng ngày", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Nếu mọi thứ đều hợp lệ -> cập nhật
            NhapBean bean = new NhapBean(id, TenSanPham, NhaCungCap, GiaNhap, NgayNhap, Size, Mau, SoLuong);
            NhapBal bal = new NhapBal();
            bal.updateData(bean);
            loadTable();
            JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thành công!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldGiaNhap;
    private javax.swing.JTextField jTextFieldMau;
    private javax.swing.JTextField jTextFieldNgayNhap;
    private javax.swing.JTextField jTextFieldNhaCungCap;
    private javax.swing.JTextField jTextFieldSize;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldTenSanPham;
    // End of variables declaration//GEN-END:variables
}
